### ISSUE TITLE
Can't click on buttons

### ISSUE THREAD

**Issue by neriyaco** [afrokick/muonlinejs#7]
Hi, this is a great project!

When starting the app I couldn't click on anything, after some debugging I found that the issue is in `style.less`, specifically this css rule:
```css
#root,
.app {
  height: 100%;
  display: grid;
  position: relative;
  pointer-events: none; // <-- This
}
```

I don't know why you put it there, maybe it should be on the canvas and maybe after the game initialize.
